// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemKontrolka.Services;

#nullable disable

namespace SystemKontrolka.Migrations
{
    [DbContext(typeof(KontrolkaDbContext))]
    partial class KontrolkaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("SystemKontrolka.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEditDefectTypes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEditParts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEditReports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEditUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
